export const users = [
  {
    id: 1,
    email: 'camila.ferreira.@example.com',
    password: 12345,
    firstName: 'Camila',
    lastname: 'Ferreira',
  },
  {
    id: 2,
    email: 'example2@example.com',
    password: 23457,
    firstName: 'Anna',
    lastname: 'Fernandes',
  },
  {
    id: 3,
    email: 'example3@example.com',
    password: 11111,
    firstName: 'Teresa',
    lastname: 'Marcelo',
  },
  {
    id: 4,
    email: 'example4@example.com',
    password: 12222,
    firstName: 'Salvo',
    lastname: 'Belucci',
  },
  {
    id: 5,
    email: 'example5@example.com',
    password: 13333,
    firstName: 'Camila',
    lastname: 'Ferreira',
  },
  {
    id: 6,
    email: 'example6@example.com',
    password: 14444,
    firstName: 'Carmelo',
    lastname: 'Gallo',
  },
  {
    id: 7,
    email: 'example7@example.com',
    password: 14444,
    firstName: 'Tullio',
    lastname: 'Toscani',
  },
  {
    id: 8,
    email: 'example8@example.com',
    password: 14444,
    firstName: 'Mariano',
    lastname: 'Romani',
  },
  {
    id: 9,
    email: 'example9@example.com',
    password: 14444,
    firstName: 'Ernest',
    lastname: 'Nixon',
  },
  {
    id: 10,
    email: 'example10@example.com',
    password: 1444,
    firstName: 'Michael',
    lastname: 'Stanton',
  },
  {
    id: 11,
    email: 'example11@example.com',
    password: 1144,
    firstName: 'John',
    lastname: 'Jessen',
  },
  {
    id: 11,
    email: 'test',
    password: 1234,
    firstName: 'John',
    lastname: 'Jessen',
  },
];
