export const connectionsInfo = [
  {
    city: 'Warsaw',
    country: 'PL',
    continent: 'EU',
    value: [
      {
        city: 'Paris',
        country: 'FR',
        continent: 'EU',
        prices: [88, 92, 93, 78],
        departureTime: '16-05',
        arrivalTime: '17-40',
        durration: '1.35H',
      },
      {
        city: 'New York',
        country: 'US',
        continent: 'NA',
        prices: [265, 312, 293, 199],
        departureTime: '07-10',
        arrivalTime: '19-40',
        durration: '12.30H',
      },
      {
        city: 'Berlin',
        country: 'DE',
        continent: 'EU',
        prices: [88, 76, 102, 74],
        departureTime: '15-10',
        arrivalTime: '16-15',
        durration: '1.05H',
      },
      {
        city: 'Frankfurt',
        country: 'DE',
        continent: 'EU',
        prices: [78, 102, 91, 77],
        departureTime: '20-00',
        arrivalTime: '20-50',
        durration: '0.50H',
      },
    ],
  },
  {
    city: 'Paris',
    country: 'FR',
    continent: 'EU',
    value: [
      {
        city: 'Warsaw',
        country: 'PL',
        continent: 'EU',
        prices: [68, 53, 78, 102],
        departureTime: '06-15',
        arrivalTime: '07-50',
        durration: '1.35H',
      },
      {
        city: 'New York',
        country: 'US',
        continent: 'NA',
        prices: [230, 292, 193, 267],
        departureTime: '05-20',
        arrivalTime: '15-45',
        durration: '10.25H',
      },
    ],
  },
  {
    city: 'New York',
    country: 'US',
    continent: 'NA',
    value: [
      {
        city: 'Warsaw',
        country: 'PL',
        continent: 'EU',
        prices: [348, 292, 222, 278],
        departureTime: '08-00',
        arrivalTime: '20-30',
        durration: '12.30H',
      },
      {
        city: 'Paris',
        country: 'FR',
        continent: 'EU',
        prices: [245, 321, 215, 200],
        departureTime: '10-05',
        arrivalTime: '20-30',
        durration: '10.25H',
      },
      {
        city: 'Berlin',
        country: 'DE',
        continent: 'EU',
        prices: [255, 291, 183, 257],
        departureTime: '05-20',
        arrivalTime: '17-55',
        durration: '12.35H',
      },
      {
        city: 'Frankfurt',
        country: 'DE',
        continent: 'EU',
        prices: [255, 291, 183, 257],
        departureTime: '05-20',
        arrivalTime: '17-55',
        durration: '12.35H',
      },
    ],
  },
  {
    city: 'Berlin',
    country: 'DE',
    continent: 'EU',
    value: [
      {
        city: 'Warsaw',
        country: 'PL',
        continent: 'EU',
        prices: [68, 53, 78, 102],
        departureTime: '06-15',
      },
      {
        city: 'New York',
        country: 'US',
        continent: 'NA',
        prices: [230, 292, 193, 267],
        departureTime: '06-20',
        arrivalTime: '18-55',
        durration: '12.35H',
      },
      {
        city: 'Frankfurt',
        country: 'DE',
        continent: 'EU',
        prices: [88, 122, 93, 79],
        departureTime: '13-00',
        arrivalTime: '13-50',
        durration: '0.50H',
      },
    ],
  },
  {
    city: 'Frankfurt',
    country: 'DE',
    continent: 'EU',
    value: [
      {
        city: 'Warsaw',
        country: 'PL',
        continent: 'EU',
        prices: [68, 53, 78, 102],
        departureTime: '10-15',
        arrivalTime: '11-35',
        durration: '1.20H',
      },
      {
        city: 'New York',
        country: 'US',
        continent: 'NA',
        prices: [230, 292, 193, 267],
        departureTime: '15-20',
        arrivalTime: '13-50',
        durration: '0.50H',
      },
      {
        city: 'Berlin',
        country: 'DE',
        continent: 'EU',
        prices: [78, 101, 83, 99],
        departureTime: '11-00',
        arrivalTime: '11-50',
        durration: '0.50H',
      },
    ],
  },
];

export const extraCosts = {
  basic: 0,
  plus: 15,
  premium: 25,
};
